# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab3.xdc

# IP: ip/data_mem/data_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_mem || ORIG_REF_NAME==data_mem} -quiet] -quiet

# IP: ip/inst_mem/inst_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_mem || ORIG_REF_NAME==inst_mem} -quiet] -quiet

# XDC: ip/data_mem/data_mem_ooc.xdc

# XDC: ip/inst_mem/inst_mem_ooc.xdc
